import { NextResponse } from "next/server";
import { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } from "@google/generative-ai";
import { getSecureKey } from "@/lib/api-key-manager";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const apiKey = getSecureKey();

    if (!apiKey) return NextResponse.json({ error: "API key missing" }, { status: 500 });

    const genAI = new GoogleGenerativeAI(apiKey);
    
    let prompt = "";
    let imagePart: any = null;

    if (body.image) {
      const base64Data = body.image.includes(",") ? body.image.split(",")[1] : body.image;
      
      let mimeType = "image/jpeg";
      if (body.image.includes("data:image/png")) mimeType = "image/png";
      else if (body.image.includes("data:image/webp")) mimeType = "image/webp";

      imagePart = {
        inlineData: {
          data: base64Data,
          mimeType: mimeType
        }
      };
    }

    const gender = body.gender || "user";

    // Face Scan: AI returns real JSON metrics
    let isFaceScan = false;
    if (body.customPrompt) {
      prompt = body.customPrompt;
    } else if (body.mode === "product_scan") {
      prompt = `
        You are GlowAI, a world-class dermatological assistant. 
        Analyze the scanned skincare product image provided.
        
        STRUCTURE YOUR RESPONSE AS FOLLOWS:
        
        1. **AI VERDICT**
        State clearly "✅ AI Approved" if the product seems safe and beneficial, or "⚠️ Not Recommended" if it contains harsh chemicals.

        2. **PRODUCT OVERVIEW**
        Identify the product and briefly explain what it is.

        3. **USEFUL OR HARMFUL**
        Analyze typical ingredients. State if it's safe or has harsh chemicals.

        4. **WHY USE THIS?**
        Detail benefits for a ${gender}'s skin.

        5. **WHO SHOULD AVOID THIS?**
        Mention skin types or conditions to avoid this.

        MANDATORY: 
        - End with: "Generated by GlowAI (AI Generated)".
      `;
    } else if (body.message) {
      prompt = `
        You are GlowAI, a world-class dermatological assistant. 
        User (${gender}) Question: "${body.message}"
        Provide professional, gender-specific skincare advice.
      `;
    } else if (body.mode === "face_scan" || body.image) {
      // REAL AI FACE SCAN — returns structured JSON
      isFaceScan = true;
      const { userName = "User", country = "India" } = body;
      prompt = `You are GlowAI, a certified AI dermatologist trained on thousands of clinical skin images. You MUST analyze the actual photo provided — do NOT give generic or average scores.

STEP 1 — CAREFULLY LOOK at the actual face in the photo:
- Count visible pimples, pustules, blackheads, whiteheads, red inflamed spots, cystic bumps
- Check forehead, nose, chin (T-zone) for oily shine, sebum, greasy texture
- Look at cheeks, forehead for dark patches, uneven skin tone, sunspots, hyperpigmentation
- Check under eyes for dark circles, puffiness
- Assess overall skin clarity, radiance, and health

STEP 2 — SCORE based on what you ACTUALLY SEE (not averages):
- acne: 0 = no pimples at all, 100 = severe cystic acne everywhere. Even 1-2 pimples = at least 10-15.
- oil: 0 = perfectly matte dry skin, 100 = visibly greasy/shiny all over. Slight T-zone shine = 25-40.
- pigmentation: 0 = perfectly even tone, 100 = severe dark spots everywhere. Minor uneven tone = 15-25.
- score: overall skin health score (higher = healthier skin). Calculate as: 100 - (acne*0.35 + oil*0.25 + pigmentation*0.25 + other_issues*0.15)

STEP 3 — Also detect and include these additional fields in your JSON:
- "darkCircles": integer 0-100 (under-eye darkness)
- "dryness": integer 0-100 (skin dryness/flakiness)  
- "redness": integer 0-100 (irritation/redness/rosiness)
- "pores": integer 0-100 (visible pore size)
- "texture": integer 0-100 (uneven skin texture/roughness)

Return ONLY a valid JSON object, no extra text:
{
  "score": <integer 0-100>,
  "acne": <integer 0-100>,
  "oil": <integer 0-100>,
  "pigmentation": <integer 0-100>,
  "darkCircles": <integer 0-100>,
  "dryness": <integer 0-100>,
  "redness": <integer 0-100>,
  "pores": <integer 0-100>,
  "texture": <integer 0-100>,
  "report": "<detailed markdown report for ${userName} with sections: **SKIN ANALYSIS FINDINGS** (list exactly what you observed), **ROOT CAUSES**, **DIET & HYDRATION** (local ${country} foods), **RECOMMENDED ROUTINE** (morning + night with specific products). Be specific about what you saw in this person's skin, not generic advice.>"
}`;
    } else {
      prompt = `You are GlowAI, a world-class dermatological assistant. Provide professional skincare advice.`;
    }

    const content = imagePart ? [prompt, imagePart] : [prompt];

    const safetySettings = [
      { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
    ];

    const model = genAI.getGenerativeModel({ 
      model: "gemini-2.0-flash",
      generationConfig: { 
        maxOutputTokens: 3000, 
        temperature: 0.3,
        ...(isFaceScan ? { responseMimeType: "application/json" } : {})
      },
      safetySettings,
    });

    const result = await model.generateContent(content);
    const text = result.response.text();

    if (isFaceScan) {
      try {
        // Clean potential markdown code fences from response
        const cleanText = text.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
        const parsed = JSON.parse(cleanText);
        return NextResponse.json({ 
          score: parsed.score ?? 70,
          acne: parsed.acne ?? 0,
          oil: parsed.oil ?? 0,
          pigmentation: parsed.pigmentation ?? 0,
          darkCircles: parsed.darkCircles ?? 0,
          dryness: parsed.dryness ?? 0,
          redness: parsed.redness ?? 0,
          pores: parsed.pores ?? 0,
          texture: parsed.texture ?? 0,
          report: parsed.report ?? "Analysis complete.",
          text: parsed.report ?? "Analysis complete."
        });
      } catch {
        // If JSON parse fails, return raw text
        return NextResponse.json({ text });
      }
    }

    return NextResponse.json({ text });
  } catch (err: any) {
    console.error("🔥 Next.js AI Error:", err);
    return NextResponse.json({ error: "Failed to connect to AI: " + err.message }, { status: 500 });
  }
}
