import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { getSecureKey } from "@/lib/api-key-manager";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const apiKey = getSecureKey();

    if (!apiKey) return NextResponse.json({ error: "API key missing" }, { status: 500 });

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ 
      model: "gemini-3.1-flash-lite-preview",
      generationConfig: { maxOutputTokens: 600, temperature: 0.4 }
    });

    let prompt = "";
    let imagePart: any = null;

    if (body.image) {
      const base64Data = body.image.split(",")[1];
      imagePart = {
        inlineData: {
          data: base64Data,
          mimeType: "image/jpeg"
        }
      };
    }

    const gender = body.gender || "user";

    if (body.mode === "product_scan") {
      prompt = `
        You are Velmora, a world-class dermatological assistant. 
        Analyze the scanned skincare product image provided.
        
        STRUCTURE YOUR RESPONSE AS FOLLOWS:
        
        1. **PRODUCT OVERVIEW**
        Identify the product and briefly explain what it is.

        2. **USEFUL OR HARMFUL**
        Analyze typical ingredients. State if it's safe or has harsh chemicals.

        3. **WHY USE THIS?**
        Detail benefits for a ${gender}'s skin.

        4. **WHO SHOULD AVOID THIS?**
        Mention skin types or conditions (e.g. sensitive, pregnancy) to avoid this.

        5. **MAIN PURPOSE**
        Core problem solved.

        MANDATORY: 
        - End with: "Generated by Velmora (AI Generated)".
      `;
    } else if (body.message) {
      prompt = `
        You are Velmora, a world-class dermatological assistant. 
        User (${gender}) Question: "${body.message}"
        Provide professional, gender-specific skincare advice.
      `;
    } else {
      const { acne = 0, oil = 0, pigmentation = 0, score = 0, userName = "User" } = body;
      prompt = `
        Analyze this skin scan for ${userName} (${gender}).
        MANDATORY: Provide a personalized report specifically tailored for a ${gender}.
        
        Metrics:
        - Glow Score: ${score}/100
        - Acne Level: ${acne}%
        - Oiliness: ${oil}%
        - Pigmentation: ${pigmentation}%

        Sections: DIET, MORNING ROUTINE, NIGHT ROUTINE, PRO GLOW TIPS.
        Tailor the advice for ${gender} skin physiology.
      `;
    }

    const content = imagePart ? [prompt, imagePart] : [prompt];
    const result = await model.generateContent(content);
    const text = result.response.text();

    return NextResponse.json({ text });
  } catch (err: any) {
    console.error("🔥 Next.js AI Error:", err);
    return NextResponse.json({ error: "Failed to connect to AI" }, { status: 500 });
  }
}
